// 🔹 User Types
export const USER_TYPES = {
  ASSOCIATE: "ASSOCIATE",
  EMPLOYEE: "EMPLOYEE",
};

// 🔹 User Roles
export const USER_ROLES = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  OPS_ADMIN: "OPS_ADMIN",
  FINANCE_ADMIN: "FINANCE_ADMIN",
  SUPPORT_ADMIN: "SUPPORT_ADMIN",
  USER: "USER",
  SYSTEM: "SYSTEM",
};

// 🔹 User Statuses
export const USER_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DEACTIVATED: "DEACTIVATED",
  SUSPENDED: "SUSPENDED",
  OFFBOARDED: "OFFBOARDED",
  TERMINATED: "TERMINATED",
};

// 🔹 Enrollment Types
export const USER_ENROLLMENT_TYPES = {
  NEW_REGISTRATION: "NEW_REGISTRATION",
  AGREEMENT_RENEWAL: "AGREEMENT_RENEWAL",
  AMENDMENT: "AMENDMENT",
};

// 🔹 Enrollment Flow Modes
export const USER_ENROLLMENT_FLOW_MODES = {
  NEW: "NEW",
  RESUME: "RESUME",
};

// Enrollment Progress
export const ENROLLMENT_PROGRESS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  UNDER_COMPLIANCE_REVIEW: "UNDER_COMPLIANCE_REVIEW",
  COMPLIANCE_APPROVED: "COMPLIANCE_APPROVED",
  AGREEMENT_PENDING: "AGREEMENT_PENDING",
  AGREEMENT_SIGNED: "AGREEMENT_SIGNED",
  READY_FOR_ACTIVATION: "READY_FOR_ACTIVATION",
  ACTIVATED: "ACTIVATED",
  REJECTED: "REJECTED",
  ON_HOLD: "ON_HOLD",
};

// Enrollment Status
export const ENROLLMENT_STATUS = {
  AWAITING_SUBMISSION: "AWAITING_SUBMISSION",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  ON_HOLD: "ON_HOLD",
};

// Progress to Status Mapping
export const ENROLLMENT_PROGRESS_STATUS_MAP = {
  [ENROLLMENT_PROGRESS.DRAFT]: ENROLLMENT_STATUS.AWAITING_SUBMISSION,

  [ENROLLMENT_PROGRESS.SUBMITTED]: ENROLLMENT_STATUS.UNDER_REVIEW,

  [ENROLLMENT_PROGRESS.PAYMENT_PENDING]: ENROLLMENT_STATUS.AWAITING_SUBMISSION,
  [ENROLLMENT_PROGRESS.PAYMENT_COMPLETED]: ENROLLMENT_STATUS.UNDER_REVIEW,

  [ENROLLMENT_PROGRESS.UNDER_COMPLIANCE_REVIEW]: ENROLLMENT_STATUS.UNDER_REVIEW,
  [ENROLLMENT_PROGRESS.COMPLIANCE_APPROVED]: ENROLLMENT_STATUS.APPROVED,

  [ENROLLMENT_PROGRESS.AGREEMENT_PENDING]: ENROLLMENT_STATUS.APPROVED,
  [ENROLLMENT_PROGRESS.AGREEMENT_SIGNED]: ENROLLMENT_STATUS.APPROVED,

  [ENROLLMENT_PROGRESS.READY_FOR_ACTIVATION]: ENROLLMENT_STATUS.APPROVED,
  [ENROLLMENT_PROGRESS.ACTIVATED]: ENROLLMENT_STATUS.APPROVED,

  [ENROLLMENT_PROGRESS.REJECTED]: ENROLLMENT_STATUS.REJECTED,
  [ENROLLMENT_PROGRESS.ON_HOLD]: ENROLLMENT_STATUS.ON_HOLD,
};

// 🔹 Steps
export const STEPS = {
  AUTH: "AUTH",
  KYC: "KYC",
  PAN_BANK: "PAN_BANK",
  PERSONAL: "PERSONAL",
  KIOSK: "KIOSK",
  PREVIEW: "PREVIEW",
};

// 🔹 Enrollment Sections (Flow per User Type)
export const USER_ENROLLMENT_SECTIONS = {
  [USER_TYPES.ASSOCIATE]: [
    STEPS.AUTH,
    STEPS.KYC,
    STEPS.PAN_BANK,
    STEPS.PERSONAL,
    STEPS.KIOSK,
    STEPS.PREVIEW,
  ],

  [USER_TYPES.EMPLOYEE]: [
    STEPS.AUTH,
    STEPS.KYC,
    STEPS.PAN_BANK,
    STEPS.PERSONAL,
    STEPS.PREVIEW,
  ],
};

// 🔹 Step Modes (Control Flow)
export const USER_ENROLLMENT_STEP_MODES = {
  NEXT: "NEXT",
  SAVE_DRAFT: "SAVE_DRAFT",
  SUBMIT: "SUBMIT",
  FINAL_SUBMIT: "FINAL_SUBMIT",
};

// 🔹 User Actions based on Type & Status
export const USER_ACTIONS_CONFIG = {
  [USER_TYPES.ASSOCIATE]: {
    [USER_STATUSES.ACTIVE]: ["DEACTIVATE", "SUSPEND", "OFFBOARD"],
    [USER_STATUSES.DEACTIVATED]: ["REACTIVATE"],
  },

  [USER_TYPES.EMPLOYEE]: {
    [USER_STATUSES.ACTIVE]: ["DEACTIVATE", "SUSPEND", "TERMINATE"],
    [USER_STATUSES.DEACTIVATED]: ["REACTIVATE"],
  },
};

// 🔹 Evolution Stages
export const EVOLUTION_STAGES = {
  COMPLIANCE: "COMPLIANCE",
  AGREEMENT: "AGREEMENT",
  ACTIVATION: "ACTIVATION",
};
